name: Continuous Integration

on:
  push:
    branches:
      - main  # This will trigger the workflow when changes are pushed to the 'main' branch.
  pull_request:
    branches:
      - main  # This will trigger the workflow when a PR is opened/updated against the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # This can be changed to windows-latest or macos-latest depending on your environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (example for a Node.js project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
